project:
  type: website
  output-dir: docs

website:
  title: "Herbert Lizama"
  navbar:
    right:
      - href: index.qmd
        text: "Inicio"
      - href: posts/index.qmd
        text: "Blog"
      - href: about.qmd
        text: "Sobre mí"
      - icon: github
        href: https://github.com/herbert-liz
      - icon: linkedin
        href: https://www.linkedin.com/in/herbert-lizama/
      - icon: instagram
        href: https://www.instagram.com/data.impact/
      - icon: youtube
        href: https://www.youtube.com/channel/UCU5MNQV6OPd4r9quPcHaXjQ
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css